baseURL: https://reitan4742.com:51008/
languageCode: ja-jp
title: My Portfolio
theme: colordrop

author:
  name: Reiya Matsumoto
  job: graduate student
  image: profile.jpg
  github: https://github.com/reitan4742/

taxonomies:
  tag: tags

menu:
  # main:
  #   - identifier: blog
  #     name: Blog
  #     url: blog/
  #     weight: 2
  #   - identifier: tags
  #     name: Tags
  #     url: tags/
  #     weight: 3
  footer:
    - identifier: github
      name: github
      url: "https://github.com/reitan4742/"
      weight: 1

params:
  description: "ようこそ！！このサイトは、エンジニア志望の大学院生のポートフォリオサイトです。私が身に着けたスキルや、これまでに開発をしたアプリケーションについてまとめています。"
  siteLogo: profile.jpg 
  themeColor: "#4169e1"
  themeInverseColor: "#ffffff"
