site_name: portfolio
site_url: https://reitan4742.com

nav:
  - Home: index.md
  - About: about.md
  - Works: works.md
  - Blog:
    - blog/index.md

plugins:
  - blog:
      blog_dir: blog

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/reitan4742
  generator: false

theme:
  name: material
  language: ja
  logo: assets/profile.png
  favicon: assets/profile.jpg
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  features:
    - navigation.tracking
      # - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

copyright: Copyright &copy; 2023 Reiya Matsumoto
repo_url: https://github.com/reitan4742/portfolio
markdown_extensions:
  - admonition
